import numpy as np
import pandas as pd
import os
def ReTuRnSoMeThInG(n):
    return np.log(5)
def big_function():
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)
    np.log(5)

def main():
    p = np.log(5)
    print(f"the log of 7 is {p}")
    
    print(f"The log of this unit is a lot of text to print but we are going to make a long line {ReTuRnSoMeThInG(7)}")
    big_function()

if __name__ == "__main__":
    main()  